"""add color to crop_families

Revision ID: c1423381dde1
Revises: d3240b2210ea
Create Date: 2026-05-22 15:15:02.612414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1423381dde1'
down_revision: Union[str, Sequence[str], None] = 'd3240b2210ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_geo_filters', table_name='users')
    op.drop_index('idx_users_location', table_name='users', postgresql_where='(last_lat IS NOT NULL)')
    op.create_index(op.f('ix_users_camp_id'), 'users', ['camp_id'], unique=False)
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_last_lat'), 'users', ['last_lat'], unique=False)
    op.create_index(op.f('ix_users_last_lng'), 'users', ['last_lng'], unique=False)
    op.create_index(op.f('ix_users_last_seen'), 'users', ['last_seen'], unique=False)
    op.create_index(op.f('ix_users_province_id'), 'users', ['province_id'], unique=False)
    op.create_index(op.f('ix_users_region_id'), 'users', ['region_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_region_id'), table_name='users')
    op.drop_index(op.f('ix_users_province_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen'), table_name='users')
    op.drop_index(op.f('ix_users_last_lng'), table_name='users')
    op.drop_index(op.f('ix_users_last_lat'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_index(op.f('ix_users_camp_id'), table_name='users')
    op.create_index('idx_users_location', 'users', ['last_lat', 'last_lng'], unique=False, postgresql_where='(last_lat IS NOT NULL)')
    op.create_index('idx_users_geo_filters', 'users', ['province_id', 'district_id', 'region_id', 'camp_id'], unique=False)
    # ### end Alembic commands ###
